from __future__ import annotations

from functools import lru_cache
from typing import Iterable
from urllib.parse import urlsplit, urlunsplit

from openai import AzureOpenAI, OpenAI

from src.common.settings import get_settings


def _clean(value: str | None) -> str:
    if value is None:
        return ""
    return str(value).strip().strip('"').strip("'")


def _strip_query(url: str) -> str:
    parsed = urlsplit(url)
    return urlunsplit((parsed.scheme, parsed.netloc, parsed.path, "", ""))


def _normalize_openai_v1_base_url(base_url: str) -> str:
    url = _strip_query(_clean(base_url)).rstrip("/")

    if not url:
        return ""

    if "/openai/deployments/" in url:
        url = url.split("/openai/deployments/")[0].rstrip("/") + "/openai/v1"

    for suffix in [
        "/chat/completions",
        "/responses",
        "/embeddings",
        "/completions",
    ]:
        if url.endswith(suffix):
            url = url[: -len(suffix)].rstrip("/")

    if "/openai/v1" in url:
        url = url.split("/openai/v1")[0].rstrip("/") + "/openai/v1"
    elif url.endswith("/openai"):
        url = url + "/v1"
    else:
        url = url + "/openai/v1"

    return url.rstrip("/") + "/"


def _normalize_azure_endpoint(endpoint: str) -> str:
    url = _strip_query(_clean(endpoint)).rstrip("/")

    if "/openai" in url:
        url = url.split("/openai")[0].rstrip("/")

    return url


class AzureChatClient:
    def __init__(self):
        settings = get_settings()

        self.api_key = _clean(settings.azure_openai_api_key)
        self.base_url = _normalize_openai_v1_base_url(settings.azure_openai_base_url)
        self.chat_model = _clean(
            settings.azure_openai_chat_model or settings.azure_openai_model
        )

        if not self.api_key:
            raise RuntimeError("AZURE_OPENAI_API_KEY missing in environment settings")

        if not self.base_url:
            raise RuntimeError("AZURE_OPENAI_BASE_URL missing in environment settings")

        if not self.chat_model:
            raise RuntimeError(
                "AZURE_OPENAI_CHAT_MODEL or AZURE_OPENAI_MODEL missing in environment settings"
            )

        self.client = OpenAI(
            api_key=self.api_key,
            base_url=self.base_url,
        )

    def chat(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 500,
    ) -> str:
        response = self.client.chat.completions.create(
            model=self.chat_model,
            messages=[
                {
                    "role": "system",
                    "content": system_prompt,
                },
                {
                    "role": "user",
                    "content": user_prompt,
                },
            ],
            temperature=temperature,
            max_tokens=max_tokens,
        )

        if not response.choices:
            return "No response generated by the chat model."

        message = response.choices[0].message

        if message.content and str(message.content).strip():
            return str(message.content).strip()

        return "The chat model returned an empty response."


class AzureEmbeddingClient:
    def __init__(self):
        settings = get_settings()

        self.api_key = _clean(settings.azure_openai_embedding_api_key)
        self.raw_base_url = _clean(settings.azure_openai_embedding_base_url)
        self.model_name = _clean(settings.azure_openai_embedding_model)
        self.deployment_name = _clean(
            settings.azure_openai_embedding_deployment
            or settings.azure_openai_embedding_model
        )
        self.api_version = (
            _clean(settings.azure_openai_embedding_api_version) or "2024-02-01"
        )
        self.max_text_chars = settings.embedding_max_text_chars
        self.batch_size = max(1, settings.embedding_batch_size)

        if not self.api_key:
            raise RuntimeError(
                "AZURE_OPENAI_EMBEDDING_API_KEY missing in environment settings"
            )

        if not self.raw_base_url:
            raise RuntimeError(
                "AZURE_OPENAI_EMBEDDING_BASE_URL missing in environment settings"
            )

        if not self.deployment_name:
            raise RuntimeError(
                "AZURE_OPENAI_EMBEDDING_DEPLOYMENT missing in environment settings"
            )

        if "/openai/v1" in self.raw_base_url or ".services.ai.azure.com" in self.raw_base_url:
            self.client = OpenAI(
                api_key=self.api_key,
                base_url=_normalize_openai_v1_base_url(self.raw_base_url),
            )
        else:
            self.client = AzureOpenAI(
                api_key=self.api_key,
                azure_endpoint=_normalize_azure_endpoint(self.raw_base_url),
                api_version=self.api_version,
            )

    def _prepare_text(self, text: str) -> str:
        clean_text = " ".join(str(text).split()).strip()

        if len(clean_text) > self.max_text_chars:
            clean_text = clean_text[: self.max_text_chars]

        return clean_text

    def embed_texts(self, texts: Iterable[str]) -> list[list[float]]:
        text_list = [
            self._prepare_text(text)
            for text in texts
            if str(text).strip()
        ]

        text_list = [text for text in text_list if text]

        if not text_list:
            return []

        all_embeddings: list[list[float]] = []

        for start in range(0, len(text_list), self.batch_size):
            batch = text_list[start : start + self.batch_size]

            response = self.client.embeddings.create(
                model=self.deployment_name,
                input=batch,
            )

            batch_embeddings = [
                item.embedding
                for item in response.data
                if item.embedding
            ]

            all_embeddings.extend(batch_embeddings)

        return all_embeddings


@lru_cache(maxsize=1)
def get_llm_client() -> AzureChatClient:
    return AzureChatClient()


@lru_cache(maxsize=1)
def get_embedding_client() -> AzureEmbeddingClient:
    return AzureEmbeddingClient()